<a href="https://colab.research.google.com/github/Roshni19sharma99/LLM/blob/main/RNN_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [122]:
from tensorflow.keras.preprocessing.text import one_hot

In [123]:
Sent = [
    'The cat sat on the warm windowsill, watching the birds fly by.',

    'She bought fresh vegetables from the local farmer’s market.',

    'A strong wind knocked over the garden gnome last night.',

    'The astronaut looked down at Earth, feeling both awe and loneliness.'
]

In [124]:
##define the vocabulary size
voc_size = 10000

In [125]:
one_hot_repr = [one_hot(words,voc_size) for words in Sent]
one_hot_repr

[[5330, 120, 5986, 988, 5330, 5861, 3420, 1058, 5330, 8753, 8335, 2183],
 [1734, 1790, 674, 7535, 7569, 5330, 9737, 2908, 7957],
 [1638, 4377, 645, 486, 5672, 5330, 6733, 9449, 9230, 2931],
 [5330, 2102, 3317, 4703, 9091, 8683, 5642, 9249, 8033, 1350, 9816]]

In [126]:
##word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences
import numpy as np


In [127]:
sent_length = 30
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0 5330  120 5986  988 5330 5861 3420 1058 5330 8753
  8335 2183]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0 1734 1790  674 7535 7569 5330 9737
  2908 7957]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0 1638 4377  645  486 5672 5330 6733 9449
  9230 2931]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0 5330 2102 3317 4703 9091 8683 5642 9249 8033
  1350 9816]]


In [128]:
dim = 10
model = Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_shape=(sent_length,)))
model.compile(optimizer = 'adam',loss = 'mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [129]:
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_10 (Embedding)             │ (None, 30, 10)              │         100,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [130]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step


array([[[-0.03111434,  0.02994943, -0.00515999, ..., -0.04209473,
          0.0267409 , -0.01461345],
        [-0.03111434,  0.02994943, -0.00515999, ..., -0.04209473,
          0.0267409 , -0.01461345],
        [-0.03111434,  0.02994943, -0.00515999, ..., -0.04209473,
          0.0267409 , -0.01461345],
        ...,
        [-0.02651802,  0.01406001, -0.0213662 , ..., -0.01501646,
          0.04687294, -0.02065138],
        [ 0.00053651, -0.02809833, -0.04686522, ..., -0.01299013,
         -0.00643564,  0.03540838],
        [ 0.04393805, -0.03561968, -0.02256668, ...,  0.02196368,
          0.00664861, -0.02519567]],

       [[-0.03111434,  0.02994943, -0.00515999, ..., -0.04209473,
          0.0267409 , -0.01461345],
        [-0.03111434,  0.02994943, -0.00515999, ..., -0.04209473,
          0.0267409 , -0.01461345],
        [-0.03111434,  0.02994943, -0.00515999, ..., -0.04209473,
          0.0267409 , -0.01461345],
        ...,
        [ 0.04490528,  0.00823531, -0.01461153, ..., -

In [131]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0, 5330,  120, 5986,  988,
       5330, 5861, 3420, 1058, 5330, 8753, 8335, 2183], dtype=int32)

In [132]:
single_input = np.expand_dims(embedded_docs[0], axis=0)
output = model.predict(single_input)
output

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step


array([[[-3.1114340e-02,  2.9949430e-02, -5.1599853e-03, -2.8229261e-02,
         -1.2388937e-03, -9.4914548e-03, -4.5537293e-02, -4.2094730e-02,
          2.6740897e-02, -1.4613450e-02],
        [-3.1114340e-02,  2.9949430e-02, -5.1599853e-03, -2.8229261e-02,
         -1.2388937e-03, -9.4914548e-03, -4.5537293e-02, -4.2094730e-02,
          2.6740897e-02, -1.4613450e-02],
        [-3.1114340e-02,  2.9949430e-02, -5.1599853e-03, -2.8229261e-02,
         -1.2388937e-03, -9.4914548e-03, -4.5537293e-02, -4.2094730e-02,
          2.6740897e-02, -1.4613450e-02],
        [-3.1114340e-02,  2.9949430e-02, -5.1599853e-03, -2.8229261e-02,
         -1.2388937e-03, -9.4914548e-03, -4.5537293e-02, -4.2094730e-02,
          2.6740897e-02, -1.4613450e-02],
        [-3.1114340e-02,  2.9949430e-02, -5.1599853e-03, -2.8229261e-02,
         -1.2388937e-03, -9.4914548e-03, -4.5537293e-02, -4.2094730e-02,
          2.6740897e-02, -1.4613450e-02],
        [-3.1114340e-02,  2.9949430e-02, -5.1599853e-03, -2.